### ISSUE TITLE
Marine Microbes: new tracker layout

### ISSUE THREAD

**Issue by mradochonski** [muccg/bpa-metadata#100]
Same tracker design as for Antibiotic Resistant Pathogens.

**Comment by mradochonski** [comment]
@grahame do we have any spec how should the tracker for MM look like? Columns, status, technology?

**Comment by grahame** [comment]
@mradochonski it looks like the model in MM is a bit different - see `class SampleStateTrack` in `models.py`. I've not got a strong opinion, there's no existing data so we're not bound by it. We could potentially make it look a bit more like the way Sepsis thinks about things - eg. change it so there are classes to track `16s`, `18s`, etc data.

**Comment by grahame** [comment]
Maciej has landed the prototype.
