### ISSUE TITLE
Deprecate sepsis tracker API - migrate fields to sample API

### ISSUE THREAD

**Issue by mradochonski** [muccg/bpa-metadata#105]
The tracker API needs to be deprecated, these models should not be exposed via the REST API. However, there is important metadata in those models that needs to be exposed in the sample API.

An initial change needs to add any 'tracker' fields to the 'sample' API to allow for users to migrate prior to finally deprecating the tracker API.

**Comment by grahame** [comment]
Landed in the v3 API, which has hit 1.0.0 - closing.
