### ISSUE TITLE
Base: contextual data matrix ajaxification and ckanification

### ISSUE THREAD

**Issue by aahunter** [muccg/bpa-metadata#170]
The contextual data matrix in base needs a refresh to make is use ajax paging and use ckan where possible.

https://data.bioplatforms.com/bpa/base/contextual/samplematrix

**Comment by grahame** [comment]
Hey @sztamas, yes all the data is on the organisation `bpa-base`

Have a look at `bpa-ingest` for a list of fields, under `bpaingest/projects/base` (`contextual.py` has everything). Everything from the latest contextual metadata has been ingested. Look at `ingest.py` for a list of datatypes, there are three: `amplicons', `metagenomics`, `metatranscriptomics`.

**Comment by sztamas** [comment]
Added all the columns that were there in the legacy page + "Data Type".

The only column I couldn't find is the last one "Total N".
@grahame do you know anything about that one?
Maybe it was missed or is it a calculated field?

**Comment by grahame** [comment]
This has been landed on prod.
