### ISSUE TITLE
Marine Microbes Metatranscriptomic sequences

### ISSUE THREAD

**Issue by sthysel** [muccg/bpa-metadata#2]
There be Metatranscriptomic sequences in addition to the metagenomic and amplicon sequences for Marine Microbes

**Comment by sthysel** [comment]
You requested Metatranscriptomic tabs be added, we don't have those kind of sequences yet do we ? Do you have an idea of the metadata associated with those.

Or do we already have those in the existing sets and I need to sub-categorise them ?

**Comment by sthysel** [comment]
For the MM project we don’t have any of this data yet.  I assume the metadata will be similar to that of the metagenomic data.

Cheers,

Jason

**Comment by sthysel** [comment]
OK, I'll add facilities for that based on current metagenomics, we
ll fine tune later if necessary.

**Comment by sthysel** [comment]
For the MM project we don’t have any of this data yet.  I assume the metadata will be similar to that of the metagenomic data.

**Comment by sthysel** [comment]
OK, I'll add facilities for that based on current metagenomics, we
ll fine tune later if necessary.

**Comment by aahunter** [comment]
This is on hold until data starts coming in.

**Comment by grahame** [comment]
Tracked by a more recent ticket.
