### ISSUE TITLE
django-secure is deprecated

### ISSUE THREAD

**Issue by aahunter** [muccg/bpa-metadata#22]
https://docs.djangoproject.com/en/1.8/releases/1.8/#security-enhancements

**Comment by sthysel** [comment]
removed requirement, kept configuration as is assuming that stays the same

**Comment by aahunter** [comment]
Slightly more involved:

https://github.com/muccg/rdrf/pull/18

**Comment by sthysel** [comment]
Config seems the same, added below for completeness sake as rdrf has them, values are defaults, so there is no functional difference.

SECURE_SSL_HOST = env.get("secure_ssl_host", False)                                                                                                                                                         
SECURE_REDIRECT_EXEMPT = env.getlist("secure_redirect_exempt", [])

**Comment by aahunter** [comment]
SECURE_FRAME_DENY needs to be removed.
checksecure needs to be replaced with check --deploy

**Comment by aahunter** [comment]
Might want to consider click jacking middleware, django.middleware.clickjacking.XFrameOptionsMiddleware, https://docs.djangoproject.com/en/1.8/ref/clickjacking/.
