### ISSUE TITLE
Marine Microbes Quality Sheets

### ISSUE THREAD

**Issue by sthysel** [muccg/bpa-metadata#3]
What fields from the quality sheet needs to be available ?

My understanding is columns A-H from the "Pass or Fail" sheet.

https://docs.google.com/spreadsheets/d/1hy8xKP5B9MlrE5so9GPUhfKQaWW_NrMEHLsx1Od5FX8/edit#gid=794141224

MM_QC.xlsx

**Comment by sthysel** [comment]
I think you can exclude columns C & D.  For column H, it might be better to change Good and Bad to be Pass and Fail.  What do you think?

**Comment by sthysel** [comment]
OK thanks. Yes I guess Pass and Fail sounds better, its also in line with other boolean things we display, I think.

**Comment by sztamas** [comment]
@sthysel is this a completely new view?
I will have to create a model, admin, import/exporter for it, right?
When creating the model, is the sample related to `MMSample` somehow? Is the `Sample ID` column the `bpa_id` column on `MMSample`?

Thanks

**Comment by sthysel** [comment]
@sztamas Yup that's all correct. Also a public view :-)

**Comment by grahame** [comment]
@sztamas I'm not sure where this ticket is at. There's a bunch of MM contextual data which we need to ingest, I guess this is just another metadata type. My instinct would be to make this ticket part of moving MM to CKAN as source of truth, does that sound good to you?
