### ISSUE TITLE
Sepsis Track RNA (HiSeq) import some of the columns remain empty.

### ISSUE THREAD

**Issue by sthysel** [muccg/bpa-metadata#43]
Q1.I tested the Import button on the "Track RNA (HiSeq)" several times but there are some issues.

I've attached the csv file I used here as well as the screen shot.

Some of the columns remain empty.

**Comment by sthysel** [comment]
![2016-09-07-075947_1566x77_scrot](https://cloud.githubusercontent.com/assets/148329/18303064/ce5eda56-750d-11e6-873e-85e6dd26f86c.png)

Column names should be respected.

**Comment by aahunter** [comment]
Waiting for feedback from Mabel.

**Comment by aahunter** [comment]
Feedback from Mabel:

> I don't want the column headings to change. What happened was I downloaded the column headings from the public view of the samples tracker, so it was not the right headings.
