### ISSUE TITLE
Sepsis: replicate should be a number from 1 -10

### ISSUE THREAD

**Issue by aahunter** [muccg/bpa-metadata#44]
Report from Mabel:

The replicate should be a number from 1 -10 (I think we will only have 6 replicate at the most).

At the moment the only number it registers is 1 or 0.

I've attached the screen shot for you.

**Comment by grahame** [comment]
I don't think the attachment worked?

**Comment by aahunter** [comment]
![image](https://cloud.githubusercontent.com/assets/2595116/18303069/d613fdda-750d-11e6-822d-335fbdbd8ed9.png)

**Comment by aahunter** [comment]
[Sample tracking test.csv.txt](https://github.com/muccg/bpa-metadata/files/458499/Sample.tracking.test.csv.txt)

**Comment by aahunter** [comment]
Attached files from bug report, csv renamed to get by gh extension whitelist.
