### ISSUE TITLE
Mi Seq Track List now empty

### ISSUE THREAD

**Issue by shilob** [muccg/bpa-metadata#56]
MiSeq API endpoint used to have data, now returning empty list:

https://downloads.bioplatforms.com/antibiotic_resistant_pathogens/api/v2/track_miseq/

Thanks in advance for looking into this.

**Comment by sztamas** [comment]
We believe this is because BPA Project Managers were editing that data.
The data was probably deleted when you tried to access it.
If you access the API endpoint now it does have data, so we can't reproduce the problem.

**Comment by grahame** [comment]
Closing as believe this to be resolved, @shilob please re-open if necessar.
