### ISSUE TITLE
Login screen needs attention

### ISSUE THREAD

**Issue by mradochonski** [muccg/bpa-metadata#87]
![selection_023](https://cloud.githubusercontent.com/assets/1464710/19299247/cc6c7634-9085-11e6-9f89-ebd2d880cf9c.png)

**Comment by grahame** [comment]
Good spot. I'd been wondering why we even have that - logging in outside of the admin has no use?

**Comment by mradochonski** [comment]
Good question, will investigate

**Comment by mradochonski** [comment]
Looks like it doesn't have any use. It takes you to /accounts/profile/ which is not even served. Remove the link?
