### ISSUE TITLE
Add consistent "last_modified" data to the API, allow querying based upon it

### ISSUE THREAD

**Issue by grahame** [muccg/bpa-metadata#90]
This would allow users to get a list of changed items since they last gathered data from the API.

**Comment by mradochonski** [comment]
last_modified on all API endpoints, not the tracker ones.

**Comment by mradochonski** [comment]
Check the existing last_modified and see how it is populated

**Comment by mradochonski** [comment]
Endpoints missing last_modified:
/antibiotic_resistant_pathogens/api/v2/project/
/antibiotic_resistant_pathogens/api/v2/bpa_ids/

**Comment by mradochonski** [comment]
All other endpoints have "last_modified" field and it works as expected.

**Comment by grahame** [comment]
Maybe we should just write up some quick docs on how to sort by lastmodified then?

**Comment by grahame** [comment]
Handled by v3 API
